let mdtgver = "0.17α";

let tdCss = {};
let tdCssText = "";
let tdCssTextMin = "";
let addHtmlDark = false;

function cssOutput () {
  tdCssText = "";
  Object.keys(tdCss).forEach((key) => {
    if (tdCss[key].length === 0) delete tdCss[key];
    else {
      tdCssText = tdCssText + `${key}{`
      tdCss[key].forEach((e) => {
        tdCssText = tdCssText + e;
      })
      tdCssText = tdCssText + "}\n"
      if(addHtmlDark == true) {
        tdCssText = tdCssText + `html.dark ${key}{`
      tdCss[key].forEach((e) => {
        tdCssText = tdCssText + e;
      })
      tdCssText = tdCssText + "}\n"
      }
    }
  })
  $('.td-preview').contents().find('style').text(tdCssText);
  $('.td-css-obj').val(JSON.stringify(tdCss));
  tdCssText = tdCssText + `/*Generated by https://mdtg.sbmr.in v${mdtgver}*/`
  $('.td-css-text').val(tdCssText);
  tdCssTextMin = tdCssText.replace(/\r?\n/g, "");
  $('.td-css-text-min').val(tdCssTextMin);
};

$(function () {
  $('#mdtg-ver').text(mdtgver);
  $('.td-theme-dark').addClass('displaynone');

  $('input[name="td-theme"]:radio').change(function () {
    let val = $(this).val();
    if (val == 1) {
      $('.td-preview').contents().find('html').addClass('dark');
      /*$('.td-theme-light').addClass('displaynone');
      $('.td-theme-dark').removeClass('displaynone');*/
    } else {
      $('.td-preview').contents().find('html').removeClass('dark');
      /*$('.td-theme-light').removeClass('displaynone');
      $('.td-theme-dark').addClass('displaynone');*/
    }
  });

  $('input#add-html-dark').change(function () {
    if ($(this).prop("checked") == true) {
      addHtmlDark = true;
      cssOutput();
    } else {
      addHtmlDark = false;
      cssOutput();
    }
  });

  $('input.td-css').change(function () {
    let tdSel = $(this).data('sel');
    let tdProp = $(this).data('prop');
    let val = $(this).val();
    $(`input[data-sel="${tdSel}"][data-prop="${tdProp}"]`).val(val);
    if (tdSel in tdCss === false) tdCss[tdSel] = [];
    tdCss[tdSel].forEach((e) => {
      if (e.startsWith(`${tdProp}:`)) {
        let index = tdCss[tdSel].indexOf(e)
        tdCss[tdSel].splice(index, 1)
      }
    })
    if (val) tdCss[tdSel].push(`${tdProp}:${val};`);
    tdCss[tdSel].sort()
    cssOutput();
  });

  $('input[type="button"].td-css-import').click(function () {
    try {
      tdCss = JSON.parse($('input[type="text"].td-css-import').val());
      Object.keys(tdCss).forEach((key) => {
        tdCssText = tdCssText + `${key}{`
        tdCss[key].forEach((e) => {
          let propVal = e.split(':');
          let prop = propVal[0];
          let val = propVal[1].replace(/;/g, "");
          $(`input[data-sel="${key}"][data-prop="${prop}"]`).val(val);
          tdCssText = tdCssText + e;
        })
        tdCssText = tdCssText + "}\n"
      })
      $('.td-preview').contents().find('style').text(tdCssText);
      $('.td-css-obj').val(JSON.stringify(tdCss));
      tdCssText = tdCssText + `/*Generated by https://mdtg.sbmr.in v${mdtgver}*/`
      $('.td-css-text').val(tdCssText);
      tdCssTextMin = tdCssText.replace(/\r?\n/g, "");
      $('.td-css-text-min').val(tdCssTextMin);
    } catch (error) {
      alert("インポートに失敗しました");
    }
  })
});